### ISSUE TITLE
Remove me from watching all orbit-apps repos

### ISSUE THREAD

**Issue by Sleepful** [pixelunion/elixir-launchdarklyapi#117]
After leaving orbit-apps my GH account remained subscribed to all orbit-apps repos. This is annoying and clutters my notifications whenever activity occurs in any of these repos. I have tried removing myself from "Watchers" of as many repos as possible, but to this day I still get spam.

**Comment by phildenhoff** [comment]
Hi @Sleepful — sorry that you're getting notifications that aren't helpful.

You can unwatch repositories in bulk by visiting https://github.com/watching. [GitHub has written a blog post about it](https://github.blog/changelog/2022-01-12-unwatch-all-repositories-owned-by-a-given-user-or-organization/). I don't see you as a member of the organization, but if you are, you can leave in [your Organization settings](https://github.com/settings/organizations).

If neither of those help, please reach back out and I'll dig into why you're still getting notifications.
